export enum CardholderStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  COMPLIANCE_DECLINE = 'COMPLIANCE_DECLINE',
  ADMIN_DECLINE = 'ADMIN_DECLINE',
  ERROR = 'ERROR',
  SUSPENDED = 'SUSPENDED',
  OFFBOARDED = 'OFFBOARDED',
}
